/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fizzBuzz

import greetings.App

fun forFizzBuzz() {
    for(i in 1..100) {
        if ((i % 3 == 0) && (i % 5 == 0)) {
            println("FizzBuzz")
        } else if(i % 3 == 0) {
            println("Fizz")
        } else if(i % 5 == 0) {
            println("Buzz")
        }
    }
}

fun main() {
    println(App().greeting)
    forFizzBuzz()
}
